'use client';
import {useCallback,useEffect,useState} from 'react';
import {Clock3,Laptop,Monitor,Pencil,RefreshCw,ShieldCheck,Trash2,UserRound,X} from 'lucide-react';
import {apiFetch} from '@/lib/api-client';
import {useAuthStore} from '@/store/auth';
import styles from './devices.module.css';
type Device={id:string;device_name:string;status:'active'|'revoked';assigned_employee_id?:string|null;assigned_employee_name?:string|null;created_at:string;last_seen_at?:string|null};
type Pending={id:string;device_name:string;requested_employee_name:string;created_at:string;expires_at:string};
type User={id:string;full_name?:string|null;name?:string|null;email?:string|null};
const userName=(user:User)=>user.full_name||user.name||user.email||'Unnamed employee';
const date=(value:string)=>new Date(value).toLocaleString([],{dateStyle:'medium',timeStyle:'short'});
export default function DevicesPage(){
 const {token,user}=useAuthStore(),isSuperAdmin=user?.role==='superadmin',[devices,setDevices]=useState<Device[]>([]),[pending,setPending]=useState<Pending[]>([]),[users,setUsers]=useState<User[]>([]),[assignments,setAssignments]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busyId,setBusyId]=useState(''),[refreshing,setRefreshing]=useState(false),[editing,setEditing]=useState<Device|null>(null),[editName,setEditName]=useState(''),[editEmployee,setEditEmployee]=useState('');
 const load=useCallback(async(showSpinner=false)=>{if(!token)return;if(showSpinner)setRefreshing(true);try{const [a,b]=await Promise.all([apiFetch<Response>('/api/devices',{headers:{Authorization:`Bearer ${token}`}}),apiFetch<Response>('/api/devices/pending',{headers:{Authorization:`Bearer ${token}`}})]),[active,waiting]=await Promise.all([a.json(),b.json()]);if(!a.ok)throw new Error(active.error||'Failed to load devices');if(!b.ok)throw new Error(waiting.error||'Failed to load pending devices');setDevices(Array.isArray(active)?active:[]);setPending(Array.isArray(waiting)?waiting:[]);setError('')}finally{if(showSpinner)setRefreshing(false)}},[token]);
 useEffect(()=>{void load().catch(e=>setError(e.message));if(token)void apiFetch<Response>('/api/users',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{const data=await r.json();if(r.ok)setUsers(Array.isArray(data)?data:[])});const timer=setInterval(()=>void load().catch(()=>{}),5000);return()=>clearInterval(timer)},[load,token]);
 async function approve(request:Pending){setBusyId(request.id);setError('');try{const response=await apiFetch<Response>('/api/devices/pending',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:request.id,assignedEmployeeId:assignments[request.id]||null})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to approve device');await load()}catch(e:any){setError(e.message)}finally{setBusyId('')}}
 async function revoke(device:Device){if(!window.confirm(`Revoke ${device.device_name}? The installed agent will no longer be able to upload.`))return;setBusyId(device.id);setError('');try{const response=await apiFetch<Response>('/api/devices',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:device.id,action:'revoke'})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to revoke device');await load()}catch(e:any){setError(e.message)}finally{setBusyId('')}}
 function beginEdit(device:Device){setEditing(device);setEditName(device.device_name);setEditEmployee(device.assigned_employee_id||'');setError('')}
 async function saveEdit(){if(!editing)return;setBusyId(editing.id);setError('');try{const response=await apiFetch<Response>('/api/devices',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:editing.id,action:'edit',deviceName:editName,assignedEmployeeId:editEmployee||null})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to update device');setEditing(null);await load()}catch(e:any){setError(e.message)}finally{setBusyId('')}}
 async function deleteDevice(device:Device){if(!window.confirm(`Permanently delete ${device.device_name}? Its credential will stop working immediately and this cannot be undone.`))return;setBusyId(device.id);setError('');try{const response=await apiFetch<Response>('/api/devices',{method:'DELETE',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:device.id})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to delete device');await load()}catch(e:any){setError(e.message)}finally{setBusyId('')}}
 return <main className={styles.page}><header className={styles.header}><div><span className={styles.eyebrow}>Device management</span><h1><Monitor size={28}/>Devices</h1><p>Review installation requests, assign employees, and manage enrolled computers.</p></div><button className={styles.refresh} onClick={()=>void load(true).catch(e=>setError(e.message))} disabled={refreshing}><RefreshCw size={16} className={refreshing?styles.spin:''}/>{refreshing?'Refreshing':'Refresh'}</button></header>
 <div className={styles.stats}><div><ShieldCheck/><span><strong>{pending.length}</strong> awaiting approval</span></div><div><Laptop/><span><strong>{devices.filter(d=>d.status==='active').length}</strong> active devices</span></div><div><UserRound/><span><strong>{devices.filter(d=>d.assigned_employee_name).length}</strong> assigned</span></div></div>{error&&<div role="alert" className={styles.error}>{error}</div>}
 <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Pending approval</h2><p>Employee-entered names help you choose the correct account.</p></div><span className={styles.count}>{pending.length}</span></div>{!pending.length?<div className={styles.empty}><ShieldCheck/><strong>All caught up</strong><span>No computers are waiting for approval.</span></div>:<div className={styles.pendingList}>{pending.map(request=><article className={styles.request} key={request.id}><div className={styles.deviceIcon}><Laptop/></div><div className={styles.requestIdentity}><strong>{request.device_name}</strong><span><UserRound size={14}/>{request.requested_employee_name||'Name not supplied'}</span></div><div className={styles.requested}><Clock3 size={14}/><span>Requested<br/><strong>{date(request.created_at)}</strong></span></div><label className={styles.assign}><span>Assign employee</span><select value={assignments[request.id]||''} onChange={e=>setAssignments(v=>({...v,[request.id]:e.target.value}))}><option value="">Select an employee</option>{users.map(user=><option key={user.id} value={user.id}>{userName(user)}</option>)}</select></label><button className={styles.primary} disabled={busyId===request.id} onClick={()=>void approve(request)}>{busyId===request.id?'Approving…':'Approve device'}</button></article>)}</div>}</section>
 <section className={styles.panel}><div className={styles.panelTitle}><div><h2>Enrolled devices</h2><p>Computers with permanent protected credentials.</p></div><span className={styles.count}>{devices.length}</span></div>{!devices.length?<div className={styles.empty}><Laptop/><strong>No enrolled devices</strong><span>Approved computers will appear here.</span></div>:<div className={styles.tableWrap}><table><thead><tr><th>Computer</th><th>Status</th><th>Assigned employee</th><th>Enrolled</th><th>Last seen</th><th><span className={styles.srOnly}>Actions</span></th></tr></thead><tbody>{devices.map(device=><tr key={device.id}><td><strong>{device.device_name}</strong></td><td><span className={`${styles.status} ${device.status==='active'?styles.active:styles.revoked}`}>{device.status}</span></td><td>{device.assigned_employee_name||<span className={styles.muted}>Unassigned</span>}</td><td>{date(device.created_at)}</td><td>{device.last_seen_at?date(device.last_seen_at):<span className={styles.muted}>Never</span>}</td><td><div className={styles.rowActions}>{device.status==='active'&&<button className={styles.revoke} disabled={busyId===device.id} onClick={()=>void revoke(device)}>Revoke</button>}{isSuperAdmin&&<><button className={styles.iconButton} title="Edit device" aria-label={`Edit ${device.device_name}`} disabled={busyId===device.id} onClick={()=>beginEdit(device)}><Pencil size={15}/></button><button className={styles.deleteButton} title="Delete device" aria-label={`Delete ${device.device_name}`} disabled={busyId===device.id} onClick={()=>void deleteDevice(device)}><Trash2 size={15}/></button></>}</div></td></tr>)}</tbody></table></div>}</section>
 {isSuperAdmin&&editing&&<div className={styles.modalBackdrop} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}><form className={styles.modal} onSubmit={e=>{e.preventDefault();void saveEdit()}}><div className={styles.modalHeader}><div><span className={styles.eyebrow}>Super admin</span><h2>Edit device</h2></div><button type="button" className={styles.closeButton} aria-label="Close" onClick={()=>setEditing(null)}><X size={18}/></button></div><label><span>Computer name</span><input required maxLength={120} value={editName} onChange={e=>setEditName(e.target.value)}/></label><label><span>Assigned employee</span><select value={editEmployee} onChange={e=>setEditEmployee(e.target.value)}><option value="">Unassigned</option>{users.map(employee=><option key={employee.id} value={employee.id}>{userName(employee)}</option>)}</select></label><div className={styles.modalActions}><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className={styles.primary} disabled={!editName.trim()||busyId===editing.id}>{busyId===editing.id?'Saving…':'Save changes'}</button></div></form></div>}</main>
}
