'use client';
import { useCallback,useEffect,useState } from 'react';
import { Monitor,ShieldCheck } from 'lucide-react';
import { apiFetch } from '@/lib/api-client';
import { useAuthStore } from '@/store/auth';
type Device={id:string;device_name:string;status:'active'|'revoked';assigned_employee_name?:string|null;created_at:string;last_seen_at?:string|null};
type Pending={id:string;device_name:string;created_at:string;expires_at:string};
export default function DevicesPage(){
 const {token}=useAuthStore();const [devices,setDevices]=useState<Device[]>([]),[pending,setPending]=useState<Pending[]>([]),[users,setUsers]=useState<any[]>([]);const [assignments,setAssignments]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!token)return;const [a,b]=await Promise.all([apiFetch<Response>('/api/devices',{headers:{Authorization:`Bearer ${token}`}}),apiFetch<Response>('/api/devices/pending',{headers:{Authorization:`Bearer ${token}`}})]);const [active,waiting]=await Promise.all([a.json(),b.json()]);if(!a.ok)throw new Error(active.error||'Failed to load devices');if(!b.ok)throw new Error(waiting.error||'Failed to load pending devices');setDevices(Array.isArray(active)?active:[]);setPending(Array.isArray(waiting)?waiting:[]);},[token]);
 useEffect(()=>{void load().catch(e=>setError(e.message));if(token)void apiFetch<Response>('/api/users',{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(data=>setUsers(Array.isArray(data)?data:[]));const timer=setInterval(()=>void load().catch(()=>{}),5000);return()=>clearInterval(timer);},[load,token]);
 async function approve(request:Pending){setBusy(true);setError('');try{const response=await apiFetch<Response>('/api/devices/pending',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:request.id,assignedEmployeeId:assignments[request.id]||null})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Failed to approve device');await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function revoke(device:Device){if(!window.confirm(`Revoke ${device.device_name}?`))return;const response=await apiFetch<Response>('/api/devices',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:device.id,action:'revoke'})});if(!response.ok){setError((await response.json()).error||'Failed to revoke device');return}await load()}
 const cell={padding:12,borderTop:'1px solid #ddd'};return <div style={{maxWidth:1100}}><h1 style={{display:'flex',alignItems:'center',gap:10}}><Monitor size={28}/> Devices</h1><p>Run the installer on a company computer, then approve its request here. Permanent credentials are exchanged automatically.</p>
 <section style={{background:'#fff',border:'1px solid #e4e7ec',borderRadius:14,padding:20,margin:'20px 0'}}><h2 style={{marginTop:0,display:'flex',gap:8,alignItems:'center'}}><ShieldCheck size={20}/> Pending approval</h2>{!pending.length?<p>No computers are waiting for approval.</p>:pending.map(request=><div key={request.id} style={{display:'flex',alignItems:'center',gap:10,padding:'12px 0',borderTop:'1px solid #eee',flexWrap:'wrap'}}><strong style={{minWidth:220}}>{request.device_name}</strong><span>Requested {new Date(request.created_at).toLocaleString()}</span><select value={assignments[request.id]||''} onChange={e=>setAssignments(v=>({...v,[request.id]:e.target.value}))} style={{padding:8}}><option value="">Unassigned</option>{users.map(user=><option key={user.id} value={user.id}>{user.full_name||user.name||user.email}</option>)}</select><button disabled={busy} onClick={()=>void approve(request)}>Approve</button></div>)}</section>{error&&<p role="alert" style={{color:'#b42318'}}>{error}</p>}
 <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',background:'white'}}><thead><tr><th>Name</th><th>Status</th><th>Assigned employee</th><th>Created</th><th>Last seen</th><th></th></tr></thead><tbody>{devices.map(device=><tr key={device.id}>{[device.device_name,device.status,device.assigned_employee_name||'Unassigned',new Date(device.created_at).toLocaleString(),device.last_seen_at?new Date(device.last_seen_at).toLocaleString():'Never'].map((value,index)=><td key={index} style={cell}>{value}</td>)}<td style={cell}>{device.status==='active'&&<button onClick={()=>void revoke(device)}>Revoke</button>}</td></tr>)}</tbody></table></div></div>
}
