'use client';
import { apiFetch } from '@/lib/api-client';
import { useEffect, useMemo, useState } from 'react';
import { useAuthStore } from '@/store/auth';
import { useRouter } from 'next/navigation';

const S: Record<string, React.CSSProperties> = {
  page:{minHeight:'100vh',background:'#F7F8FB',color:'#0A0A0A',padding:'28px 32px'}, card:{border:'1px solid rgba(10,10,10,.1)',background:'#FFF',borderRadius:16,padding:'18px 20px',boxShadow:'0 18px 48px rgba(15,23,42,.06)'}, input:{padding:'8px 10px',borderRadius:10,border:'1px solid rgba(10,10,10,.14)',background:'#FFF'}, button:{padding:'9px 14px',borderRadius:10,border:0,background:'#0050B0',color:'#FFF',fontWeight:700,cursor:'pointer'}, table:{width:'100%',borderCollapse:'collapse'}, th:{padding:'10px 12px',textAlign:'left',color:'rgba(10,10,10,.48)',fontSize:11,textTransform:'uppercase',borderBottom:'1px solid #eee'}, td:{padding:12,borderBottom:'1px solid #eee',verticalAlign:'top',fontSize:13}
};
const LABELS:Record<string,string>={large_transfer_threshold:'Large transfer',mass_download_detected:'Mass download',mass_copy_to_usb_detected:'Mass USB copy',external_upload_detected:'External upload','Blocked Website':'Blocked website','Blocked App':'Blocked application'};
function threshold(type:string){if(type==='large_transfer_threshold')return [100,'MB'];if(type==='mass_download_detected')return [40,'files'];if(type==='mass_copy_to_usb_detected')return [25,'files'];return null;}
function severity(e:any){const t=threshold(e.eventType),n=parseFloat(String(e.value||''));if(!t||!Number.isFinite(n))return e.eventType==='external_upload_detected'?3:1;const ratio=n/Number(t[0]);return ratio>=5?3:ratio>=2?2:1;}

export default function SecurityReportPage(){
  const {token}=useAuthStore(),router=useRouter();
  const [events,setEvents]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[employeeId,setEmployeeId]=useState(''),[eventType,setEventType]=useState(''),[applied,setApplied]=useState({employeeId:'',eventType:''});
  useEffect(()=>{if(token)apiFetch<Response>('/api/users',{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(d=>setUsers(Array.isArray(d)?d:[]));},[token]);
  async function load(){if(!token)return;const p=new URLSearchParams({limit:'100'});if(employeeId)p.set('employeeId',employeeId);if(eventType)p.set('eventType',eventType);const r=await apiFetch<Response>(`/api/security-events?${p}`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok){const d=await r.json();setEvents(Array.isArray(d)?d:[]);setApplied({employeeId,eventType});}}
  useEffect(()=>{void load();},[token]);
  const types=useMemo(()=>Array.from(new Set(['large_transfer_threshold','mass_download_detected','mass_copy_to_usb_detected','external_upload_detected',...events.map(e=>e.eventType).filter(Boolean)])),[events]);
  const grouped=useMemo(()=>{const m=new Map<string,any>();for(const e of events){const key=`${e.employeeId||e.employeeName}|${e.eventType}|${Math.floor(new Date(e.createdAt).getTime()/300000)}`,old=m.get(key),sev=severity(e);if(!old)m.set(key,{...e,count:1,severity:sev});else{old.count++;if(sev>old.severity)Object.assign(old,e,{count:old.count,severity:sev});}}return [...m.values()].sort((a,b)=>b.severity-a.severity||+new Date(b.createdAt)-+new Date(a.createdAt));},[events]);
  const rows=grouped.map(e=>[e.employeeName||e.employeeId||'',new Date(e.createdAt).toLocaleString(),e.eventType,e.value||'',e.count,e.actionTaken||'']);
  function csv(){const data=[['Employee','Time','Event Type','Value','Occurrences','Status'],...rows].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),url=URL.createObjectURL(new Blob([data],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='security-report-filtered.csv';a.click();URL.revokeObjectURL(url);}
  function pdf(){const w=window.open('','_blank','width=900,height=800');if(!w)return;w.document.write(`<h2>Security Report — filtered results</h2><table border="1" cellspacing="0" cellpadding="6">${rows.map(r=>`<tr>${r.map(v=>`<td>${String(v)}</td>`).join('')}</tr>`).join('')}</table>`);w.document.close();w.print();}
  const person=users.find(u=>u.id===applied.employeeId)?.name;
  return <div style={S.page}><button style={S.button} onClick={()=>router.back()}>← Back to Reports</button><h1>Security Report</h1><p style={{color:'#667085'}}>Prioritized security events. Repeated events within five minutes are grouped.</p><div style={S.card}>
    <div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}><select style={S.input} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">All employees</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select style={S.input} value={eventType} onChange={e=>setEventType(e.target.value)}><option value="">All event types</option>{types.map(t=><option key={t} value={t}>{LABELS[t]||t.replaceAll('_',' ')}</option>)}</select><button style={S.button} onClick={load}>Apply filters</button><button style={S.button} onClick={csv}>Export CSV</button><button style={S.button} onClick={pdf}>Export PDF</button></div>
    <p style={{fontSize:12,color:'#667085'}}>Active filters: {person||'All employees'} · {LABELS[applied.eventType]||applied.eventType.replaceAll('_',' ')||'All event types'} · Exports contain these filtered, grouped results.</p>
    <div style={{overflowX:'auto'}}><table style={S.table}><thead><tr><th style={S.th}>Priority</th><th style={S.th}>Employee</th><th style={S.th}>Latest event</th><th style={S.th}>Event type</th><th style={S.th}>Value / threshold</th><th style={S.th}>Status</th></tr></thead><tbody>{grouped.map(e=>{const t=threshold(e.eventType),color=e.severity===3?['#FEE4E2','#B42318']:e.severity===2?['#FEF0C7','#B54708']:['#E8F1FF','#0050B0'];return <tr key={`${e.id}-${e.count}`}><td style={S.td}><span style={{background:color[0],color:color[1],borderRadius:99,padding:'4px 8px',fontWeight:700}}>{e.severity===3?'High':e.severity===2?'Medium':'Review'}</span></td><td style={{...S.td,fontWeight:650}}>{e.employeeName||e.employeeId||'—'}</td><td style={S.td}>{new Date(e.createdAt).toLocaleString()}{e.count>1&&<div style={{color:'#B54708',fontWeight:700}}>{e.count} similar events</div>}</td><td style={S.td}>{LABELS[e.eventType]||e.eventType.replaceAll('_',' ')}</td><td style={S.td}><strong>{e.value||'—'}</strong>{t&&<div style={{color:'#667085'}}>Trigger: {t[0]} {t[1]}</div>}</td><td style={S.td}>{String(e.actionTaken||'Pending review').replaceAll('_',' ')}</td></tr>;})}{!grouped.length&&<tr><td style={{...S.td,textAlign:'center',padding:36}} colSpan={6}>No security events match these filters.</td></tr>}</tbody></table></div>
  </div></div>;
}
